### ISSUE TITLE
Executing "Usage Example" => Error: No dat here

### ISSUE THREAD

**Issue by serapath** [maxogden/dat-core#26]
Do I need to pass in a leveldb?
The readme says something about

> (default is `require('leveldown')`)

I do

``` javascript
var dat = require('dat-core')

var db = dat('./test')

db.put('hello', 'world', function (err) { // insert value 
  if (err) return handle(err) // something went wrong 
  db.get('hello', function (err, result) {
    if (err) return handle(err) // something went wrong 
    console.log(result)   // prints result 
    console.log(db.head) // the 'head' of the database graph (a hash) 
  })
})

// function handle (err) { console.error(err); }
```

and get

```
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: No dat here
    at /home/serapath/EXPERIMENTS/DAT_CORE/node_modules/dat-core/index.js:213:44
    at FSReqWrap.cb [as oncomplete] (fs.js:212:19)
```

**Comment by mafintosh** [comment]
did you `dat init` in the `./test` folder?

**Comment by serapath** [comment]
nope, i wasn't aware that i need `dat` to use `dat-core`.
I just tried an `npm install dat -g`, but ran into problems during installation. `npm install dat` fails too.
Maybe I can post that on the `dat` repo instead?
- `npm --version` => 3.1.2
- `node --version` => v2.3.4

**Comment by max-mapper** [comment]
@serapath you can call `db.init` from dat-core: https://github.com/maxogden/dat-core#dbinitcb, i think thats what @mafintosh meant

**Comment by serapath** [comment]
Hm, probably I'm doing something stupid.

``` javascript
// [./index.js]
var dat = require('dat-core');
var db = dat('./test');
db.init(function(){console.log(arguments);});
```

`$> node index.js`

> events.js:141
>      throw er; // Unhandled 'error' event
>            ^
> Error: No dat here
> ...

But `var db = dat('./test')` throws anyway.
I now solved it by writing:

``` javascripting
var dat = require('dat-core');
var db = dat('./test', {createIfMissing:true});
```

I'm not sure if that's how it's meant to be, but if so, then an update of the **usage example** might be helpful.

**Comment by mafintosh** [comment]
Ah yea. init should probably do that for you. I'll do a fix for that

**Comment by okdistribute** [comment]
how about this? https://github.com/maxogden/dat-core/pull/30
