### ISSUE TITLE
multiprocess live bug

### ISSUE THREAD

**Issue by max-mapper** [maxogden/dat-core#39]
```
admin@dathub:~/src/sleep-irc/data$ taco-nginx --name datircserver dat serve --readonly
Listening on port 54786 (readonly)
/home/admin/src/dat-core/lib/multiprocess.js:162
        res.cb(err)
            ^
TypeError: undefined is not a function
    at Array.<anonymous> (/home/admin/src/dat-core/lib/multiprocess.js:162:13)
    at eval [as _decode] (eval at <anonymous> (/home/admin/src/dat-core/node_modules/pbs/node_modules/generate-function/index.js:55:21), <anonymous>:38:22)
    at Decoder._pushMessage (/home/admin/src/dat-core/node_modules/pbs/decoder.js:130:10)
    at Decoder._parseMissing (/home/admin/src/dat-core/node_modules/pbs/decoder.js:102:19)
    at Decoder._parse (/home/admin/src/dat-core/node_modules/pbs/decoder.js:143:23)
    at Decoder._write (/home/admin/src/dat-core/node_modules/pbs/decoder.js:193:10)
    at doWrite (/home/admin/src/dat-core/node_modules/pbs/node_modules/readable-stream/lib/_stream_writable.js:279:12)
    at writeOrBuffer (/home/admin/src/dat-core/node_modules/pbs/node_modules/readable-stream/lib/_stream_writable.js:266:5)
    at Writable.write (/home/admin/src/dat-core/node_modules/pbs/node_modules/readable-stream/lib/_stream_writable.js:211:11)
    at Duplexify._write (/home/admin/src/dat-core/node_modules/duplexify/index.js:200:22)
```

**Comment by max-mapper** [comment]
we should also make sure on the client dat that the pull stream emits a proper error if the remote side crashes
